language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"

before_install:
  - pip install pycodestyle

install:
  - pip install .

script:
  - pycodestyle --show-source aspace
