# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'pip install twine setuptools wheel'
- script: 'python setup.py sdist bdist_wheel'

- task: TwineAuthenticate@0
  inputs:
    artifactFeeds: 'ArchivesSpace-Migrations'

- script: 'python -m twine upload -r ArchivesSpace-Migrations --config-file $(PYPIRC_PATH) dist/*'
