import enum
from collections import namedtuple


AgentTypeInfo = namedtuple('AgentTypeInfo', ['agent_type', 'api_endpoint'])


class AgentType(enum.Enum):
    # pylint: disable=E1101
    @property
    def agent_type(self) -> str:
        return self.value.agent_type

    @property
    def api_endpoint(self) -> str:
        return self.value.api_endpoint
    # pylint: enable=E1101

    PERSON = AgentTypeInfo('agent_person', '/agents/people')

    FAMILY = AgentTypeInfo('agent_family', '/agents/families')

    CORPORATE_ENTITY = AgentTypeInfo(
        'agent_corporate_entity', 
        '/agents/corporate_entities'
    )

    SOFTWARE = AgentTypeInfo('software', '/agents/software')


class AgentNameOrder(enum.Enum):
    INVERTED = 'inverted'
    DIRECT = 'direct'


class LinkedAgentRole(enum.Enum):
    CREATOR = 'creator'
    SOURCE = 'source'
    SUBJECT = 'subject'


class LinkedAgentArchivalRecordRelator(enum.Enum):
    r"""
    Generated from http://localhost:8080/enumerations?id=1 using a terrible
    jQuery statement.
    """

    ACTOR = 'act'
    ADAPTER = 'adp'
    AUTHOR_OF_AFTERWORD_COLOPHON_ETC_ = 'aft'
    ANALYST = 'anl'
    ANIMATOR = 'anm'
    ANNOTATOR = 'ann'
    BIBLIOGRAPHIC_ANTECEDENT = 'ant'
    APPLICANT = 'app'
    AUTHOR_IN_QUOTATIONS_OR_TEXT_ABSTRACTS = 'aqt'
    ARCHITECT = 'arc'
    ARTISTIC_DIRECTOR = 'ard'
    ARRANGER = 'arr'
    ARTIST = 'art'
    ASSIGNEE = 'asg'
    ASSOCIATED_NAME = 'asn'
    ATTRIBUTED_NAME = 'att'
    AUCTIONEER = 'auc'
    AUTHOR_OF_DIALOG = 'aud'
    AUTHOR_OF_INTRODUCTION_ETC_ = 'aui'
    AUTHOR_OF_SCREENPLAY_ETC_ = 'aus'
    AUTHOR = 'aut'
    BINDING_DESIGNER = 'bdd'
    BOOKJACKET_DESIGNER = 'bjd'
    BOOK_DESIGNER = 'bkd'
    BOOK_PRODUCER = 'bkp'
    BLURB_WRITER = 'blw'
    BINDER = 'bnd'
    BOOKPLATE_DESIGNER = 'bpd'
    BOOKSELLER = 'bsl'
    CONCEPTOR = 'ccp'
    CHOREOGRAPHER = 'chr'
    COLLABORATOR = 'clb'
    CLIENT = 'cli'
    CALLIGRAPHER = 'cll'
    COLORIST = 'clr'
    COLLOTYPER = 'clt'
    COMMENTATOR = 'cmm'
    COMPOSER = 'cmp'
    COMPOSITOR = 'cmt'
    CONDUCTOR = 'cnd'
    CINEMATOGRAPHER = 'cng'
    CENSOR = 'cns'
    CONTESTANT_APPELLEE = 'coe'
    COLLECTOR = 'col'
    COMPILER = 'com'
    CONSERVATOR = 'con'
    CONTESTANT = 'cos'
    CONTESTANT_APPELLANT = 'cot'
    COVER_DESIGNER = 'cov'
    COPYRIGHT_CLAIMANT = 'cpc'
    COMPLAINANT_APPELLEE = 'cpe'
    COPYRIGHT_HOLDER = 'cph'
    COMPLAINANT = 'cpl'
    COMPLAINANT_APPELLANT = 'cpt'
    CREATOR = 'cre'
    CORRESPONDENT = 'crp'
    CORRECTOR = 'crr'
    CONSULTANT = 'csl'
    CONSULTANT_TO_A_PROJECT = 'csp'
    COSTUME_DESIGNER = 'cst'
    CONTRIBUTOR = 'ctb'
    CONTESTEE_APPELLEE = 'cte'
    CARTOGRAPHER = 'ctg'
    CONTRACTOR = 'ctr'
    CONTESTEE = 'cts'
    CONTESTEE_APPELLANT = 'ctt'
    CURATOR_OF_AN_EXHIBITION = 'cur'
    COMMENTATOR_FOR_WRITTEN_TEXT = 'cwt'
    DISTRIBUTION_PLACE = 'dbp'
    DEFENDANT = 'dfd'
    DEFENDANT_APPELLEE = 'dfe'
    DEFENDANT_APPELLANT = 'dft'
    DEGREE_GRANTOR = 'dgg'
    DISSERTANT = 'dis'
    DELINEATOR = 'dln'
    DANCER = 'dnc'
    DONOR = 'dnr'
    DEPICTED = 'dpc'
    DEPOSITOR = 'dpt'
    DRAFTSMAN = 'drm'
    DIRECTOR = 'drt'
    DESIGNER = 'dsr'
    DISTRIBUTOR = 'dst'
    DATA_CONTRIBUTOR = 'dtc'
    DEDICATEE = 'dte'
    DATA_MANAGER = 'dtm'
    DEDICATOR = 'dto'
    DUBIOUS_AUTHOR = 'dub'
    EDITOR = 'edt'
    ENGRAVER = 'egr'
    ELECTRICIAN = 'elg'
    ELECTROTYPER = 'elt'
    ENGINEER = 'eng'
    ETCHER = 'etr'
    EVENT_PLACE = 'evp'
    APPRAISER = 'exp'
    FACSIMILIST = 'fac'
    FIELD_DIRECTOR = 'fld'
    FILM_EDITOR = 'flm'
    FORMER_OWNER = 'fmo'
    FUNDER = 'fnd'
    FIRST_PARTY = 'fpy'
    FORGER = 'frg'
    GEOGRAPHIC_INFORMATION_SPECIALIST = 'gis'
    GRAPHIC_TECHNICIAN = 'grt'
    HONOREE = 'hnr'
    HOST = 'hst'
    ILLUSTRATOR = 'ill'
    ILLUMINATOR = 'ilu'
    INSCRIBER = 'ins'
    INVENTOR = 'inv'
    INSTRUMENTALIST = 'itr'
    INTERVIEWEE = 'ive'
    INTERVIEWER = 'ivr'
    LABORATORY = 'lbr'
    LIBRETTIST = 'lbt'
    LABORATORY_DIRECTOR = 'ldr'
    LEAD = 'led'
    LIBELEE_APPELLEE = 'lee'
    LIBELEE = 'lel'
    LENDER = 'len'
    LIBELEE_APPELLANT = 'let'
    LIGHTING_DESIGNER = 'lgd'
    LIBELANT_APPELLEE = 'lie'
    LIBELANT = 'lil'
    LIBELANT_APPELLANT = 'lit'
    LANDSCAPE_ARCHITECT = 'lsa'
    LICENSEE = 'lse'
    LICENSOR = 'lso'
    LITHOGRAPHER = 'ltg'
    LYRICIST = 'lyr'
    MUSIC_COPYIST = 'mcp'
    METADATA_CONTACT = 'mdc'
    MANUFACTURE_PLACE = 'mfp'
    MANUFACTURER = 'mfr'
    MODERATOR = 'mod'
    MONITOR = 'mon'
    MARBLER = 'mrb'
    MARKUP_EDITOR = 'mrk'
    MUSICAL_DIRECTOR = 'msd'
    METAL_ENGRAVER = 'mte'
    MUSICIAN = 'mus'
    NARRATOR = 'nrt'
    OPPONENT = 'opn'
    ORIGINATOR = 'org'
    ORGANIZER_OF_MEETING = 'orm'
    OTHER = 'oth'
    OWNER = 'own'
    PATRON = 'pat'
    PUBLISHING_DIRECTOR = 'pbd'
    PUBLISHER = 'pbl'
    PROJECT_DIRECTOR = 'pdr'
    PROOFREADER = 'pfr'
    PHOTOGRAPHER = 'pht'
    PLATEMAKER = 'plt'
    PERMITTING_AGENCY = 'pma'
    PRODUCTION_MANAGER = 'pmn'
    PRINTER_OF_PLATES = 'pop'
    PAPERMAKER = 'ppm'
    PUPPETEER = 'ppt'
    PROCESS_CONTACT = 'prc'
    PRODUCTION_PERSONNEL = 'prd'
    PERFORMER = 'prf'
    PROGRAMMER = 'prg'
    PRINTMAKER = 'prm'
    PRODUCER = 'pro'
    PRODUCTION_PLACE = 'prp'
    PRINTER = 'prt'
    PROVIDER = 'prv'
    PATENT_APPLICANT = 'pta'
    PLAINTIFF_APPELLEE = 'pte'
    PLAINTIFF = 'ptf'
    PATENTEE = 'pth'
    PLAINTIFF_APPELLANT = 'ptt'
    PUBLICATION_PLACE = 'pup'
    RUBRICATOR = 'rbr'
    RECORDIST = 'rcd'
    RECORDING_ENGINEER = 'rce'
    RECIPIENT = 'rcp'
    REDAKTOR = 'red'
    RENDERER = 'ren'
    RESEARCHER = 'res'
    REVIEWER = 'rev'
    REPOSITORY = 'rps'
    REPORTER = 'rpt'
    RESPONSIBLE_PARTY = 'rpy'
    RESPONDENT_APPELLEE = 'rse'
    RESTAGER = 'rsg'
    RESPONDENT = 'rsp'
    RESPONDENT_APPELLANT = 'rst'
    RESEARCH_TEAM_HEAD = 'rth'
    RESEARCH_TEAM_MEMBER = 'rtm'
    SCIENTIFIC_ADVISOR = 'sad'
    SCENARIST = 'sce'
    SCULPTOR = 'scl'
    SCRIBE = 'scr'
    SOUND_DESIGNER = 'sds'
    SECRETARY = 'sec'
    SIGNER = 'sgn'
    SUPPORTING_HOST = 'sht'
    SINGER = 'sng'
    SPEAKER = 'spk'
    SPONSOR = 'spn'
    SECOND_PARTY = 'spy'
    SURVEYOR = 'srv'
    SET_DESIGNER = 'std'
    SETTING = 'stg'
    STORYTELLER = 'stl'
    STAGE_MANAGER = 'stm'
    STANDARDS_BODY = 'stn'
    STEREOTYPER = 'str'
    TECHNICAL_DIRECTOR = 'tcd'
    TEACHER = 'tch'
    THESIS_ADVISOR = 'ths'
    TRANSCRIBER = 'trc'
    TRANSLATOR = 'trl'
    TYPE_DESIGNER = 'tyd'
    TYPOGRAPHER = 'tyg'
    UNIVERSITY_PLACE = 'uvp'
    VIDEOGRAPHER = 'vdg'
    VOCALIST = 'voc'
    WRITER_OF_ACCOMPANYING_MATERIAL = 'wam'
    WOODCUTTER = 'wdc'
    WOOD_ENGRAVER = 'wde'
    WITNESS = 'wit'
    ABRIDGER = 'abr'
    ART_DIRECTOR = 'adi'
    APPELLEE = 'ape'
    APPELLANT = 'apl'
    AUTOGRAPHER = 'ato'
    BROADCASTER = 'brd'
    BRAILLE_EMBOSSER = 'brl'
    CASTER = 'cas'
    COLLECTION_REGISTRAR = 'cor'
    COURT_GOVERNED = 'cou'
    COURT_REPORTER = 'crt'
    DEGREE_SUPERVISOR = 'dgs'
    EDITOR_OF_COMPILATION = 'edc'
    EDITOR_OF_MOVING_IMAGE_WORK = 'edm'
    ENACTING_JURISDICTION = 'enj'
    FILM_DISTRIBUTOR = 'fds'
    FILM_DIRECTOR = 'fmd'
    FILMMAKER = 'fmk'
    FILM_PRODUCER = 'fmp'
    _GRT = '-grt'
    HOST_INSTITUTION = 'his'
    ISSUING_BODY = 'isb'
    JUDGE = 'jud'
    JURISDICTION_GOVERNED = 'jug'
    MEDIUM = 'med'
    MINUTE_TAKER = 'mtk'
    ONSCREEN_PRESENTER = 'osp'
    PANELIST = 'pan'
    PRAESES = 'pra'
    PRESENTER = 'pre'
    PRODUCTION_COMPANY = 'prn'
    PRODUCTION_DESIGNER = 'prs'
    RADIO_DIRECTOR = 'rdd'
    RADIO_PRODUCER = 'rpc'
    RESTORATIONIST = 'rsr'
    STAGE_DIRECTOR = 'sgd'
    SELLER = 'sll'
    TELEVISION_DIRECTOR = 'tld'
    TELEVISION_PRODUCER = 'tlp'
    VOICE_ACTOR = 'vac'
    WRITER_OF_ADDED_COMMENTARY = 'wac'
    WRITER_OF_ADDED_LYRICS = 'wal'
    WRITER_OF_ADDED_TEXT = 'wat'
    WRITER_OF_INTRODUCTION = 'win'
    WRITER_OF_PREFACE = 'wpr'
    WRITER_OF_SUPPLEMENTARY_TEXTUAL_CONTENT = 'wst'


class SubjectTermType(enum.Enum):
    CULTURAL_CONTEXT = 'cultural_context'
    FUNCTION = 'function'
    GENRE_FORM = 'genre_form'
    GEOGRAPHIC = 'geographic'
    OCCUPATION = 'occupation'
    STYLE_PERIOD = 'style_period'
    TECHNIQUE = 'technique'
    TEMPORAL = 'temporal'
    TOPICAL = 'topical'
    UNIFORM_TITLE = 'uniform_title'
